---
- hosts: all
  gather_facts: yes
  sudo: yes
#  become: True
#  become_user: root
#  remote_user: root
  roles:
   - credential

  vars_prompt:
    - name: "user_account"
      prompt: "Enter name of the user"
      private: no
      when: user_password is defined

    - name: "user_password"
      prompt: "Enter a password for the user"
      private: yes
      encrypt: "sha512_crypt" #need to have python-passlib installed in local machine before we can use it
      confirm: yes
      salt_size: 7
      append: yes
      update_password: always
      when: user_password is defined

