---

 - include_tasks: mysql_database_creation.yml
   tags: mysql_database_creation

 - include_tasks: mysql_adduser.yml
   tags: mysql_adduser

 - include_tasks: mysql_deluser.yml
   tags: mysql_deluser

 - include_tasks: mysql_updatepassword.yml
   tags: mysql_updatepassword

 - include_tasks: user_add.yml
   tags: user_add

 - include_tasks: user_del.yml
   tags: user_del

 - include_tasks: user_password.yml
   tags: user_password

 - include_tasks: user_check.yml
   tags: user_check

 - include_tasks: mysql_check.yml
   tags: mysql_check

 - include_tasks: system_info.yml
   tags: system_info
# tasks file for credential
