---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: db

- name: Create database new_user
  mysql_user: user={{ mysql_user }} password={{ mysql_password }} host={{ remote_host }}  priv={{ mysql_privileges }} append_privs=yes state=present login_host={{ db_host }} login_user={{ db_root_username }} login_password={{ db_root_password }}




