---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: db


- name: Ensure Ansible MYSQL tmp grants file
  stat:
    path: /tmp/ansiblemysql.log
  register: stat_result

- name: Ensure ansible MYSQL tmp userlist file
  stat:
    path: /tmp/ansiblemysqltest.log
  register: stat_result


- name: Deleting previous MYSQL tmp grants file
  file:
    path: /tmp/ansiblemysql.log
    state: absent

- name: Deleting previous MYSQL tmp userlist file
  file:
    path: /tmp/ansiblemysqltest.log
    state: absent

- name: USER,HOST present in MYSQL
  shell: mysql -u{{ db_root_username }} -p{{ db_root_password }} -sNe "SELECT user,host FROM user" mysql
  register: userhost


#- name:  Get Userlist from mysql server
#  shell: mysql -u{{ db_root_username }} -p{{ db_root_password }} -sNe "SELECT CONCAT('SHOW GRANTS FOR \'',user,'\'@\'',host,'\';') FROM user" mysql
#  register: mysqluserlist

#- name: Updating the report
#  shell: mysql -u{{ db_root_username }} -p{{ db_root_password }} -sNe "{{mysqluserlist.stdout}}" mysql
#  register: mysqltest

#- lineinfile: create=yes regexp="NONEXISTENTLINE" dest=/tmp/ansiblemysql.log line="{{mysqluserlist.stdout}}"  state=present 

- lineinfile: create=yes regexp="NONEXISTENTLINE" dest=/tmp/ansiblemysqltest.log line="{{userhost.stdout}}"  state=present 

#- lineinfile: create=yes regexp="NONEXISTENTLINE" dest=/tmp/ansiblemysqltest.log line="{{mysqltest.stdout}}"  state=present insertafter=EOF


- fetch:
    src: /tmp/ansiblemysqltest.log
    dest: /tmp/mysqlhost-{{ inventory_hostname }}
    flat: yes

