---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: db
    
- name: Delete database user
  mysql_user: user={{ mysql_user }}  host={{ remote_host }}  state=absent login_host={{ db_host }} login_user={{ db_root_username }} login_password={{ db_root_password }}

