---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: db


- name: Create database
  mysql_db: db={{ db_name }} state=present login_host={{ db_host }} login_user={{ db_root_username }} login_password={{ db_root_password }}
