---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: db
 
- name: Update database user password
  mysql_user: user={{ mysql_user }} password={{ mysql_password }} update_password=always  host={{ remote_host }} state=present login_host={{ db_host }} login_user={{ db_root_username }} login_password={{ db_root_password }}
