---

- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: app

- name: Ensure previous system info file present
  stat:
    path: /tmp/system_info.csv
  register: systeminfo_result

- name: Deleting previous system info file present
  file:
    path: /tmp/system_info.csv
    state: absent

- name: get device name
  set_fact:
      device_name: "{{ inventory_hostname }}"

- name: Getting ntp server info
  shell: ntpq -p | tail -1 | gawk  '{print $1}'
  register: ntpserverinfo
  ignore_errors: true 

- name: Getting yum history
  shell: yum history | head -n 4  | tail -1
  register: yumhistory
  ignore_errors: true

#- name: updating clamd
#  shell: update
#  ignore_errors: true

- name: CLAMD antivirus update definition
  shell: freshclam -V | awk '{ print substr($0, index($0,$3)) }'
  register: freshclam
  ignore_errors: true
  

- copy:
    content: |
      IPADDRESS,HOSTNAME,OSNAME,OSVERSION,PROCESSOR,ARCHITECTURE,MEMORY,NTPSERVER,CLAMDUPDATE,YUMHISTORY;
      {% for host in hostvars %}
      {%   set vars = hostvars[host|string] %}
       {{ vars.inventory_hostname }},{{ vars.ansible_hostname }},{{ vars.ansible_distribution }},{{ vars.ansible_distribution_version }},{{ vars.ansible_processor[1] }},{{ vars.ansible_architecture }},{{ (vars.ansible_memtotal_mb/1024)|round|int }}, {{ vars.ntpserverinfo.stdout }},{{ vars.freshclam.stdout.split( ) | join ('_') }}, {{ vars.yumhistory.stdout.split( ) | join ('') }} }};
      {% endfor %}
    dest: /tmp/system_info.csv
  delegate_to: localhost
