---

- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: app

- name: verify user account
  shell: grep "^{{ user_account }}:" /etc/passwd
  ignore_errors: yes
  register: user_exist

- name: create new user account
  user: name={{user_account}} password={{user_password}} groups={{group_account}} shell=/bin/bash
  when: user_exist.rc == 1
  
- name: Password expiry for new password promption
  shell: passwd -e {{ user_account }}
  when: user_exist.rc == 1

