---
- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: app

- name: verify user account
  shell: grep "^{{ user_account }}:" /etc/passwd
  ignore_errors: yes
  register: user_exist
    
- name: Removing user account
  user: name={{user_account}} state=absent remove=yes  
  when: user_exist.rc == 0
