---

- name: Dependencies of Ansible installing in remote host
  include_role:
    name: common
    tasks_from: app

- name: Ensure ansible tmp file exists
  stat:
    path: /tmp/ansibleuser.log
  register: stat_result

- name: Deleting previous file present
  file:
    path: /tmp/ansibleuser.log
    state: absent

- name: verify user account
  shell: "awk -F: '{ if($3 >= 500)  print $1}' /etc/passwd "
  register: users

- lineinfile: create=yes regexp="NONEXISTENTLINE" dest=/tmp/ansibleuser.log line="{{users.stdout}}"  state=present ####insertafter=EOF  

- fetch:
    src: /tmp/ansibleuser.log
    dest: /tmp/host-{{ inventory_hostname }}
    flat: yes

#- name: adding group in soders
#  blockinfile:
#    path: /etc/sudoers
#    block: |
#     #command not allowed for support Team
#          %support ALL = ALL, !/etc/init.d/network, !/etc/init.d/iptables, !/etc/init.d/mysqld,!/bin/su, !/bin/mount, !/bin/umount, /bin/chown, !/sbin/ifconfig, !/sbin/reboot, !/sbin/shutdown, !/sbin/halt, !/sbin/partprobe, !/sbin/service, !/bin/bash, !/usr/bin/sudo -i, !/usr/bin/sudo, !/usr/bin/vim /etc/sudoers,!/bin/vi /etc/sudoers     ##
#     #Command not allowed for release
     ##
#           %release ALL = ALL, !/etc/init.d/network, !/etc/init.d/iptables, !/bin/su, !/bin/mount, !/bin/umount, /bin/chown, !/sbin/reboot, !/sbin/shutdown, !/sbin/halt, !/sbin/partprobe, !/bin/bash, !/usr/bin/sudo -i
